# Generated by Django 6.0.4 on 2026-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsatellitedata',
            name='biomass',
        ),
        migrations.RemoveField(
            model_name='fieldsatellitedata',
            name='lai',
        ),
        migrations.RemoveField(
            model_name='fieldsatellitedata',
            name='ndbi',
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WATER_STRESSED', 'Water Stressed'), ('COMPLETED', 'Completed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
